ATTRIBUTE:
  DIM: '2D'
  NAME: 'example-data'
  FRAMEWORK: 'segmentation'
  KEYS: [image, label]
  PHASE: [train, valid, test]
  FILES_LIST: "/homes/clwang/Data/medlp_exp/segmentation/rjh_tswi/res-unet-96,96,64-CE-DCE-BN-adamw-plateau-1123_1609-Dil-Elastic-3cls/train_files"
PREPROCESS:
  LOADER:
    LoadImage:
      keys: [image, label]
      phase: [train, valid, test]
      args: {'as_closest_canonical': True}
  CHANNELER:
    AddChannel:
      keys: 'image'
      phase: [train, valid]
  ORIENTER: {}
  RESCALER: {}
  RESIZER: {}
AUGMENTATION:
  RandShiftIntensity: 
    keys: 'image'
    phase: 'train'
    args: {'offsets': 0.1, 'prob': 0.5}
  RandAdjustContrast: 
    keys: 'image'
    phase: 'train'
DATASET_TYPE:
  CacheDataset:
    phase: [train, valid]
    args: {'cache_rate': 0.1}