authorName: default
experimentName: select_hyparam_catheter
trialConcurrency: 1
maxExecDuration: 30h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
# localConfig:
#     gpuIndices: None
tuner:
    builtinTunerName: TPE
    classArgs:
      optimize_mode: maximize
      parallel_optimize: True
      constant_liar_type: min
assessor:
    builtinAssessorName: Curvefitting
    classArgs:
      epoch_num: 100
      start_step: 30
      threshold: 0.9
      gap: 3
trial:
    command: python main.py train-fcfg --config "/homes/yliu/Code/medlp/param.list"
    codeDir: .
    gpuNum: 0